import 'package:flutter/material.dart';


final black = new MaterialColor(Colors.black.value, <int, Color>{
  50: Colors.white70,
  100: Colors.black12,
  200: Colors.black26,
  300: Colors.black38,
  400: Colors.black45,
  500: Colors.black54,
  600: Colors.black54,
  700: Colors.black87,
  800: Colors.black87,
  900: Colors.black,
});


final theme = new ThemeData(

  primarySwatch: black,
  accentColor: Colors.pinkAccent,
  primaryColorBrightness: Brightness.dark,
  primaryTextTheme: const TextTheme(
    title: const TextStyle(color: Colors.white,
        fontWeight: FontWeight.bold,
        fontStyle: FontStyle.normal,
        fontSize: 30.0,
        wordSpacing: 2.0),
    headline: const TextStyle(color: Colors.black,
        fontWeight: FontWeight.bold,
        fontStyle: FontStyle.normal,
        fontSize: 25.0,
        wordSpacing: 2.0),
    button: const TextStyle(color: Colors.white,
        fontWeight: FontWeight.normal,
        fontStyle: FontStyle.normal,
        fontSize: 20.0),
    subhead: const TextStyle(color: Colors.black54,
        fontWeight: FontWeight.bold,
        fontStyle: FontStyle.italic,
        fontSize: 20.0),
    body1: const TextStyle(color: Colors.black,
        fontWeight: FontWeight.bold,
        fontStyle: FontStyle.normal,
        fontSize: 20.0),
    body2: const TextStyle(color: Colors.black54,
        fontWeight: FontWeight.bold,
        fontStyle: FontStyle.normal,
        fontSize: 20.0),
    display1: const TextStyle(color: Colors.black,
        fontWeight: FontWeight.normal,
        fontStyle: FontStyle.normal,
        fontSize: 20.0,
        wordSpacing: 2.0),
    display2: const TextStyle(color: Colors.black12,
        fontWeight: FontWeight.normal,
        fontStyle: FontStyle.normal,
        fontSize: 20.0,
        wordSpacing: 2.0),
    display3: const TextStyle(color: Colors.black38,
        fontWeight: FontWeight.normal,
        fontStyle: FontStyle.normal,
        fontSize: 20.0,
        wordSpacing: 2.0),
    display4: const TextStyle(color: Colors.black54,
        fontWeight: FontWeight.normal,
        fontStyle: FontStyle.normal,
        fontSize: 20.0,
        wordSpacing: 2.0),
    caption: const TextStyle(color: Colors.white,
        fontWeight: FontWeight.normal,
        fontStyle: FontStyle.normal,
        fontSize: 20.0,
        wordSpacing: 2.0),
  ),
  backgroundColor: Colors.white30,
  fontFamily: 'Raleway',
);